# -*- coding: utf-8 -*-
"""Python_Practice2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k62fUxlECEOVjM51DN2V8H9P8CaOqnTh

# I. Рядки (String).

1. Створити пустий рядок двома різними способами.
"""

my_empty_string = ''
my_empty_string2 = str()

"""2. Створити рядок з апострофом."""

my_string = "Це рядок з апострофом: \'"
my_string

"""3. Створити рядок з символом переходу на новий рядок та роздрукувати його в консоль."""

my_string2 = "abc.\nabc."
print(my_string2)

"""4. Зробити рядок з завдання №3 "сирим"(raw), вивести в консоль та порівняти з результатом в попередному завданні."""

my_string3 = r"abc.\nabc."
print(my_string3)

"""\*місце для коментарів щодо результатів порівняння

В завданні №3 ми вивели рядок в дві строки завдяки "\n", а оператор raw(r) ігнорує зворотню косу риску

5. Створити змінну, що буде посилатися на Ваше прізвище латинкою. Створити форматований рядок, який буде мати вигляд "My surname is ______", де на місці нижніх підкреслень буде Ваше прізвище зі змінної.
"""

name_string = 'Artemov'
output_str = 'My surname is {0}'.format(name_string)
output_str

"""6. Маючи рядок "My dog is crazy." перетворити його на список ["my", "dog", "is", "crazy"]"""

dog_str = "My dog is crazy"
split_str = dog_str.split()
split_str

"""# II. Множини (Set).

7. Створити множину без елементів. Після цого за допомогою методу додайте кілька різних елементів до множини. Чи множини є змінним типом даних?
"""

my_set = set(())
my_set.add("apple")
my_set.add(1)
my_set.add(False)
my_set

"""*місце для відповіді

Множини є змінними, до них можно додавати та видаляти

8. Створити множину, маючи список my_list = [1, 1, 2, 67, 67, 8, 9]. Пояснити, чому "зникли" деякі елементи.
"""

my_list = [1,1,2,67,67,8,9]
my_unique_set = set(my_list)
my_unique_list = list(my_unique_set)
my_unique_list

"""9. Створіть дві множини. Продемонстуйте над ними операції: обʼєднання, різниці, пересічі та симетричної різниці. Використовуйте методи, що не змінюють множини, а створюють нові."""

dataScientist = set(['Python', 'R', 'SQL', 'Git', 'Tableau', 'SAS'])
dataEngineer = set(['Python', 'Java', 'Scala', 'Git', 'SQL', 'Hadoop'])

union_set = dataEngineer.union(dataScientist)
print(union_set)
intersection_set = dataEngineer.intersection(dataScientist)
print(intersection_set)
difference_set = dataEngineer.difference(dataScientist)
print(difference_set)
symmetric_difference_set = dataEngineer.symmetric_difference(dataScientist)
print(symmetric_difference_set)

"""10. Створіть множину з пʼяти елементів. За допомогою спеціального методу, вилучіть три елементи один за одним з множини. Чи може гарантуватися порядок елементів у множинах?"""

graphicDesigner = {'InDesign', 'Photoshop', 'Acrobat', 'Premiere', 'Bridge'}
graphicDesigner.pop()
graphicDesigner.pop()
graphicDesigner.pop()
print(graphicDesigner)

"""*місце для відповіді

№8
Множини не приймают дублювання, бо вони унікальні
№10
Порядок елементів в множинні  гарантується

# III. Словники (Dictionary).

11. Створіть пустий словник двома способами.
"""

empty = {}
empty_dict = dict()

"""12. До одного зі словників вище додайте чотири пари елементів такі, щоб їхні ключі були різних типів."""

empty_dict['Int'] = 1
empty_dict['Float'] = 3.14
empty_dict['Boolean'] = False
empty_dict['Tuple'] = (1,2)
empty_dict

"""*чи може список бути ключем? а значенням? чому?

Список не може бути ключем, бо

13. Використовуючи той самий словник, отримайте по ключу будь-яке значення з наявних. Тепер видаліть цю пару ключ-значення. Спробуйте знову отримати значення по цьому ж ключу. Використовуючи спеціальний метод, виправте помилку.
"""

empty_dict.get('Tuple')
empty_dict.pop('Tuple')
print(empty_dict)
empty_dict.get('Tuple',(1,3))

"""# IV. Оператори порівняння та логічні оператори. Умови.

14. Створіть цілочисленну змінну зі своїм щасливим або улюбленим числом. Напишіть код, який би автоматизовував наступну задачу.

Якщо число парне, помножте його на 2 та виведіть результат на екран.

Але якщо число непарне, помножте його на 3 та додайте 1 і виведіть на екран.
"""

int_a = 12
if int_a%2 == 0:
    print(int_a*2)
else:
    print(int_a*3+1)

"""15. Створіть рядок зі своїм імʼям латинкою. Напишіть код, який би автоматизовував наступну задачу.

Якщо в імені є літера "а"
 або "i", Виведіть на екран повідомлення "A or I is in the name".



Якщо в імені є літери "o" та "n", Виведіть на екран повідомлення "O and N is in the name".

Також якщо в імені немає літери "о", але є "n", Виведіть на екран повідомлення "Only N is in the name".

В решті випадків виведіть на екран повідомлення "There is no N in the name, but there might be O".

Зверніть увагу, що, наприклад, для імені "Antonina" буде виведено два повідомлення.
"""

name_str = 'Danya'

if 'a' or 'i' in name_str:
    print("A or I is in the name")
if 'o' in name_str and 'n' in name_str:
    print("O and N are in the name")
if 'o' not in name_str and 'n' in name_str:
    print("Only N is in the name")
if 'n' not in name_str:
    print("There is no N in the name,but thre might be an O")

"""# Вітаю! Ви велика(ий) молодець, що впоралась(вся). Похваліть себе та побалуйте чимось приємним. Я Вами пишаюся."""